### ISSUE TITLE
La propiedad Total asume que todos los conceptos manejan la misma tasa

### ISSUE THREAD

**Issue by lcarrasco** [unRob/CFDI#4]
Usando un poco más la gema me tope con que la propiedad `Total` se calcula de forma dinámica de la siguiente manera:

```
def total
   @total = self.subTotal + (self.subTotal*@opciones[:tasa])
end
```

Creo que esto es incorrecto ya que asume que todo el CFDI tiene una sola tasa, ejemplo 16% de IVA, etc. cuando en realidad cada concepto puede manejar diferentes tasas, por ejemplo ciertos conceptos pueden manejar IVA al 16%, otros al 0%, otros IEPS e incluso impuestos locales como el ISH de los hoteles, etc.

Creo que hay que cambiar un poco la lógica para tomar esto en cuenta.

Saludos!

**Comment by unRob** [comment]
Esto es muy similar a #3, me parece.
